version: "3.9"
services:
  bot:
    build: ./bot/
    restart: always 
    ports:
      - "8001:8000"
    environment:
      - "FLAG=ASIS{test-flag}"
      - "CAPTCHA_SECRET=6LeVx7AqAAAAAIsqypbJJlJEMydoy5_t_fY1fEAA"
  web:
    image: nginx
    restart: always 
    ports:
      - "8000:80"
    volumes:
      - ./app/static:/var/www/html:ro
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro